openapi: 3.0.3
info:
  title: Northwind API
  description: Northwind API
  version: 1.0.0
  contact:
    name: Christopher Wilson
    email: "chris@christopherwilson.tech"
servers:
  - url: 'https://localhost/api'
    description: Local Sail Server
paths:
  /categories:
    get:
      description: Returns all categories
      summary: Gets all categories
      operationId: getAllCategories
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
      tags:
        - Categories
  /category/{id}:
    get:
      description: Get a category by ID
      summary: Get a category by its ID
      operationId: getCategoryById
      parameters:
        - name: id
          in: path
          description: Category ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Get a category by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
      tags:
        - Categories
  /category/schema:
    get:
      description: Returns the schema for the /categories endpoint
      summary: Gets the schema of the category endpoint
      operationId: getCategorySchema
      responses:
        '200':
          description: The category schema
          content:
            application/json:
              schema:
                type: object
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/GeneralError'
      tags:
        - Categories
  /customers:
    get:
      tags:
        - Customers
      description: Returns all customers
      summary: Gets all customers
      operationId: getAllCustomers
      responses:
        '200':
          description: A list of all customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
  /customer/{id}:
    get:
      tags:
        - Customers
      description: Get a customer by ID
      summary: Retrieve a specific customer by their unique ID
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          description: Customer ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Get a customer by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/GeneralError'

components:
  responses:
    OK:
      description: OK
      content:
        application/json:
          schema:
            type: object
    AuthorizationError:
      description: Authorization information may be missing or invalid
      content:
        application/json:
          schema:
            type:
              object
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type:
              object
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'
    NotFound:
      description: Data not Found
      content:
        application/json:
          schema:
            type: object
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        picture:
          type: string
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int32
        companyName:
          type: string
        contactName:
          type: string
        contactTitle:
          type: string
        address:
          type: string
        city:
          type: string
        region:
          type: string
        postalCode:
          type: string
        country:
          type: string
        phone:
          type: string
        fax:
          type: string
    CustomerDemographic:
      type: object
      properties:
        customerTypeId:
          type: string
        customerDescription:
          type: string
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int32
        lastName:
          type: string
        firstName:
          type: string
        title:
          type: string
        titleOfCourtesy:
          type: string
        birthDate:
          type: string
        hireDate:
          type: string
        address:
          type: string
        city:
          type: string
        region:
          type: string
        postalCode:
          type: string
        country:
          type: string
        homePhone:
          type: string
        extension:
          type: string
        photo:
          type: string
        notes:
          type: string
        reportsTo:
          type: integer
          format: int32
        photoPath:
          type: string
    EmployeeTeritory:
      type: object
      properties:
        employeeId:
          type: integer
          format: int32
        territoryId:
          type: integer
          format: int32
    GeneralError:
      type: object
    OrderDetail:
      type: object
      properties:
        orderId:
          type: integer
          format: int32
        productId:
          type: integer
          format: int32
        unitPrice:
          type: integer
        quantity:
          type: integer
          format: int32
        discount:
          type: integer
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int32
        customerId:
          type: string
        employeeId:
          type: integer
          format: int32
        orderDate:
          type: string
        requiredDate:
          type: string
        shippedDate:
          type: string
        shipVia:
          type: integer
          format: int32
        freight:
          type: integer
          format: int32
        shippingName:
          type: string
        shippingAddress:
          type: string
        shippingCity:
          type: string
        shippingRegion:
          type: string
        shippingPostalCode:
          type: string
        shippingCounttry:
          type: string
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        supplierId:
          type: integer
          format: int32
        categoryId:
          type: integer
          format: int32
        quantityPerUnit:
          type: string
        unitPrice:
          type: integer
          format: int32
        unitsInStock:
          type: integer
          format: int32
        unitsOnOrder:
          type: integer
          format: int32
        reorderLevel:
          type: integer
          format: int32
        discontinued:
          type: boolean
    Region:
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
    Shipper:
      type: object
      properties:
        id:
          type: integer
          format: int32
        companyName:
          type: string
        phone:
          type: string
    Supplier:
      type: object
      properties:
        id:
          type: integer
          format: int32
        companyName:
          type: string
        contactName:
          type: string
        contactTitle:
          type: string
        address:
          type: string
        city:
          type: string
        region:
          type: string
        postalCode:
          type: string
        country:
          type: string
        phone:
          type: string
        fax:
          type: string
        homepage:
          type: string
    Territories:
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
        regionId:
          type: integer
          format: int32
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
tags:
  - name: Categories
    description: Category operations
  - name: Customers
    description: Customer operations
  - name: Employees
    description: Employee operations
  - name: Orders
    description: Order operations
  - name: Products
    description: Product operations
  - name: Regions
    description: Region operations
  - name: Shipments
    description: Shipment operations
  - name: Suppliers
    description: Supplier operations
  - name: Territories
    description: Territory operations
